Book.destroy_all

Book.create!([
	{title: "Snowcrash",
	 author: "Neil Stephenson",
	 description: "Add later.",
	 amazon_id: "1",
	 rating: 5,
	 finished_on: 10.days.ago},
	 {title: "Jayber Crow",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "2",
	    rating: 4,
	    finished_on: 4.days.ago},
	 {title: "A Timbered Choir",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "3",
	    rating: 6,
	    finished_on: 2.weeks.ago},
	 {title: "What Are People For?",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "4",
	    rating: 6,
	    finished_on: nil},   
	])
