Book.destroy_all

Book.create!([
	{title: "Snowcrash",
	 author: "Neil Stephenson",
	 description: "Only once in a great while does a writer come along who defies comparison—a writer so original he redefines the way we look at the world. Neal Stephenson is such a writer and Snow Crash is such a novel, weaving virtual reality, Sumerian myth, and just about everything in between with a cool, hip cybersensibility to bring us the gigathriller of the information age.",
	 amazon_id: "0553380958",
	 rating: 5,
	 finished_on: 10.days.ago},
	 {title: "Jayber Crow",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "2",
	    rating: 4,
	    finished_on: 4.days.ago},
	 {title: "A Timbered Choir",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "3",
	    rating: 6,
	    finished_on: 2.weeks.ago},
	 {title: "What Are People For?",
	 	author: "Wendell Berry",
	 	description: "Add later.",
	    amazon_id: "4",
	    rating: 6,
	    finished_on: nil},   
	])
